
tasks:
  - name: Terminal 1
    before: echo "Terminal 1"
    init: npm install && pip install -r requirements.txt




vscode:
  extensions:
    - vscodevim.vim
    - ms-azuretools.vscode-docker
    - eamodio.gitlens
# test some change issue2
